sudo: required

services:
  - docker

before_install:
  - docker build -t comoser/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true comoser/react-test npm test

after_success:
  - docker build -t comoser/docker-k8s-2-client ./client
  - docker build -t comoser/docker-k8s-2-api ./server
  - docker build -t comoser/docker-k8s-2-worker ./worker
  - docker build -t comoser/docker-k8s-2-nginx ./nginx
  # docker hub login
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # docker hub push images
  - docker push comoser/docker-k8s-2-client
  - docker push comoser/docker-k8s-2-api
  - docker push comoser/docker-k8s-2-worker
  - docker push comoser/docker-k8s-2-nginx

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-k8s-2"
  env: "docker-k8s-2-env"
  bucket_name: "elasticbeanstalk-eu-west-2-003651421893"
  bucket_path: "docker-k8s-2"
  on:
    branch: "master"
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY