version: '3'

services:

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
    depends_on:
      - api
      - client

  postgres:
    image: "postgres:latest"

  redis:
    image: "redis:latest"

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - ./server/.env
    volumes: 
      - ./server:/app
      - /app/node_modules
    depends_on:
      - redis
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    env_file: 
      - ./worker/.env
    volumes:
      - ./worker:/app
      - /app/node_modules
    depends_on:
      - api
